-- AlterTable
ALTER TABLE `container_movements` MODIFY `movementType` ENUM(
  'DELIVERED_TO_CUSTOMER',
  'RETURNED_FROM_CUSTOMER',
  'LOADED_TO_VEHICLE',
  'UNLOADED_FROM_VEHICLE',
  'LOST',
  'DAMAGED',
  'ADJUSTMENT',
  'OPENING_WITH_CUSTOMER',
  'OPENING_ON_HAND'
) NOT NULL;
