export enum StockType {
  OPENING = 'OPENING',
  CLOSING = 'CLOSING',
}

export enum RunStatus {
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
}

export enum PaymentMethod {
  CASH = 'CASH',
  BANK = 'BANK',
  EASYPAISA = 'EASYPAISA',
  JAZZCASH = 'JAZZCASH',
  OTHER = 'OTHER',
}

export enum DeliveryStatus {
  DELIVERED = 'DELIVERED',
  PARTIAL = 'PARTIAL',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum ContainerMovementType {
  DELIVERED_TO_CUSTOMER = 'DELIVERED_TO_CUSTOMER',
  RETURNED_FROM_CUSTOMER = 'RETURNED_FROM_CUSTOMER',
  LOADED_TO_VEHICLE = 'LOADED_TO_VEHICLE',
  UNLOADED_FROM_VEHICLE = 'UNLOADED_FROM_VEHICLE',
  LOST = 'LOST',
  DAMAGED = 'DAMAGED',
  ADJUSTMENT = 'ADJUSTMENT',
}

export enum LedgerEntryType {
  DELIVERY_SALE = 'DELIVERY_SALE',
  PAYMENT = 'PAYMENT',
  ADJUSTMENT = 'ADJUSTMENT',
  OPENING_BALANCE = 'OPENING_BALANCE',
  REFUND = 'REFUND',
}
